# Generated by Django 4.1.7 on 2023-04-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('DENIED', 'denied'), ('EXPIRED', 'expired'), ('APPROVED', 'approved'), ('TERMINATED', 'terminated'), ('COMPLETED', 'completed'), ('PENDINGCANCELLED', 'pendingcancelled')], default='PENDING', max_length=30),
        ),
    ]
