# Generated by Django 4.1.7 on 2023-04-21 21:54

from django.db import migrations, models
import django.db.models.deletion
import property.models.propdata


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to=property.models.propdata.upload_to)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.propdata')),
            ],
        ),
    ]
